// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_bart_multi
List fast_bart_multi(arma::mat y, List X_list, List X_test_list, List D_list, NumericVector alpha, NumericVector beta, List sigma_par_list, NumericVector n_tree, LogicalVector add_mean, int v_0, arma::mat sigma_0, int n_iter, int min_nodesize, int n_burn, int keep_every, NumericVector tree_iters);
RcppExport SEXP _mvbcfMT_fast_bart_multi(SEXP ySEXP, SEXP X_listSEXP, SEXP X_test_listSEXP, SEXP D_listSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP sigma_par_listSEXP, SEXP n_treeSEXP, SEXP add_meanSEXP, SEXP v_0SEXP, SEXP sigma_0SEXP, SEXP n_iterSEXP, SEXP min_nodesizeSEXP, SEXP n_burnSEXP, SEXP keep_everySEXP, SEXP tree_itersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< List >::type X_list(X_listSEXP);
    Rcpp::traits::input_parameter< List >::type X_test_list(X_test_listSEXP);
    Rcpp::traits::input_parameter< List >::type D_list(D_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type sigma_par_list(sigma_par_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_tree(n_treeSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type add_mean(add_meanSEXP);
    Rcpp::traits::input_parameter< int >::type v_0(v_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_0(sigma_0SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type min_nodesize(min_nodesizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< int >::type keep_every(keep_everySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tree_iters(tree_itersSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_bart_multi(y, X_list, X_test_list, D_list, alpha, beta, sigma_par_list, n_tree, add_mean, v_0, sigma_0, n_iter, min_nodesize, n_burn, keep_every, tree_iters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvbcfMT_fast_bart_multi", (DL_FUNC) &_mvbcfMT_fast_bart_multi, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvbcfMT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
