# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_bart_multi <- function(y, X_list, X_test_list, D_list, alpha, beta, sigma_par_list, n_tree, add_mean, v_0, sigma_0, n_iter, min_nodesize, n_burn, keep_every, tree_iters) {
    .Call(`_mvbcfMT_fast_bart_multi`, y, X_list, X_test_list, D_list, alpha, beta, sigma_par_list, n_tree, add_mean, v_0, sigma_0, n_iter, min_nodesize, n_burn, keep_every, tree_iters)
}

